下面是一段计算机学术论文中的误差分析描述,讲述了5种不同的错误类型. 请在这断后后面续写一段话,总结错误类型,并展开深入的分析,探究这些错误类型可能的原因,以及可能的改正方法.用英文续写

It can be observed that, despite significant improvements in our model, approximately 8\% of procedures and 31\% of diagnosis in test instances were still misclassified. We manually analyzed all error cases and summarized five types of errors.

\textbf{(1) Incomplete synset:} The description of mention is very different from the gold concept and requires special coding rules for mapping. For example, `神经根管封闭术 (nerve root canal sealing)' is mapped to `神经根管松解术 (nerve root canal decompression)' by our model, but the correct concept is `周围神经麻醉药注射，为了镇痛 (peripheral nerve anesthesia injection for pain relief)'. Although our model is technically reasonable, it is difficult to predict correctly without additional coding knowledge.

\textbf{(2) Different granularity:} The input mention and the correct concept have different granularities. Taking `右膝关节镜下粘连松解术 (arthroscopic adhesiolysis of the right knee joint)' as an example, the gold mapping `膝关节松解术 (knee joint lysis)' is the parent concept of the predicted candidate `关节镜膝关节松解术 (arthroscopic knee joint lysis)', properly due to some reimbursement policies. Considering special policies in the mapping process is the key to avoiding such errors.

\textbf{(3) Abbreviations and hypernyms:} Some entities contain hypernyms, and our model cannot correctly map the mention where these special names determine the main meaning. For instance, in a mention `桥本甲状腺炎 (Hashimoto's thyroiditis)', the unique meaning of the transliterated word `桥本' cannot be learned, which makes our model unable to match it with the gold concept `自身免疫性甲状腺炎 (autoimmune thyroiditis)'. This problem can be potentially solved by introducing a large medical knowledge base, containing richer hyponyms~\cite{mao2018word}.

\textbf{(4) Multiple-procedure terms:} In multi-implication cases, a mention could be mapped to multiple concepts. Although our model can correctly predict the implication number of most multi-implication mentions, nearly 21\% of operations and 32\% of diagnoses are still predicted incorrectly, resulting in incomplete recall of multiple gold concepts. For example, `筛窦癌化疗 (chemotherapy for sphenoid sinus cancer)' contains two procedure concepts: `癌 (cancer)' and `筛窦恶性肿瘤 (a malignant tumor of the sphenoid sinus)', but we extract three concepts with unnecessary `化学治疗 (chemotherapy)'. Our model can be further improved by introducing manual rules to predict the number of concepts. 

\textbf{(5) Insufficient candidate generation:} We also notice that the recall in the candidate generation stage reached about 97.5\% for operations and 91\% for diagnosis. This means that some mentions’ candidate pools do not include the gold concepts, so the candidate ranking model cannot find the correct concepts. Using a deep generative learning model to improve the recall of candidate tools will be the way to improve in the future. 